<?php 
/*****************************************************************************
 * Phloor Analytics OWA                                                      *
 *                                                                           *
 * Copyright (C) 2011 Alois Leitner                                          *
 *                                                                           *
 * This program is free software: you can redistribute it and/or modify      *
 * it under the terms of the GNU General Public License as published by      *
 * the Free Software Foundation, either version 2 of the License, or         *
 * (at your option) any later version.                                       *
 *                                                                           *
 * This program is distributed in the hope that it will be useful,           *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 * GNU General Public License for more details.                              *
 *                                                                           *
 * You should have received a copy of the GNU General Public License         *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.     *
 *                                                                           *
 * "When code and comments disagree both are probably wrong." (Norm Schryer) *
 *****************************************************************************/ 
?>
<?php

$english = array(
	"admin:plugins:category:PHLOOR" => "PHLOOR Plugins",
	"admin:plugin:settings:title" => 'Open Web Analytics Settings',

	'phloor_analytics_owa' => "Phloor Analytics OWA",
	'phloor_analytics_owa:path_to_owa:link' => 'Go to Open Web Analytics',

	'admin:statistics:phloor_analytics_owa' => 'Open Web Analytics',
	'phloor_analytics_owa:form:section:settings' => 'Settings',

	'phloor_analytics_owa:save:success' => 'Settings successfully saved. ',
	'phloor_analytics_owa:save:failure' => 'Settings could not be saved. ',

	'phloor_analytics_owa:couldnotopenowajavascript' => "Could not find the file 'modules/base/dist/owa.tracker.js' from the specified path '%s'. ",
	'phloor_analytics_owa:invalidsiteguid' => "Site guid must be a positiv integer (insert 1 if not sure) ",

	'phloor_analytics_owa:enable_tracking:label' => "Enable tracking? ",
	'phloor_analytics_owa:enable_tracking:description' => "If this option is enabled Open Web Analytics starts tracking. ",

	'phloor_analytics_owa:path_to_owa:label' => "Path to OWA installation ",
	'phloor_analytics_owa:path_to_owa:description' => "Path to the Open Web Analytics installation on a server. Please make sure that it starts with 'http://' and ends with '/'.. e.g. 'http://www.example.com/owa/'. This variable tells all OWA javascript objects (trackers, overlay's etc.) where the OWA server is located. The file 'modules/base/dist/owa.tracker.js' will be tried to be loaded from there. ",

	'phloor_analytics_owa:site_guid:label' => "Site Tracking ID",
	'phloor_analytics_owa:site_guid:description' => "Sets the Id of the site that you are tracking so that this ID will be logged as part of all events recorded by the Tracker. Site IDs are generated by the OWA admin interface whenever you add a new site to track. ",

);

add_translation("en", $english);
